# Generated by Django 4.2.3 on 2024-06-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GazeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('eye_position_right', models.CharField(max_length=10)),
                ('face_status', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('face_id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('profile', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
    ]
