# Generated by Django 4.2.3 on 2024-06-09 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazedata',
            name='face_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Face_Detection.userprofile'),
        ),
        migrations.AlterField(
            model_name='gazedata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
